import {
  Cpu, Dumbbell, Briefcase, Car, Moon, Camera, Plane, UtensilsCrossed,
  Clapperboard, Rocket, Trophy, Music, Palette, Gamepad2, Shirt, Film,
  BookOpen, Mountain, Flower, ChefHat, PenTool, Bitcoin, FlaskConical, PawPrint, Leaf,
  Bot, TrendingUp, Building2, Megaphone, GraduationCap, Languages, Microscope,
  Stethoscope, Newspaper, Video, PenLine, Drama, Laugh, Podcast, MonitorPlay,
  Disc3, Armchair, Brush, Sparkles, Footprints, Bike, Waves, Fish, Ship, Backpack,
  Tent, Snowflake, Flag, PartyPopper, Hand, Coffee, Wine, Beer, Martini, Cake,
  HeartPulse, Brain, Star, HeartHandshake, Dog, Cat, Bird, Sprout, Recycle,
  CloudSun, Dices, Spade, Crown, BookMarked, Gem, Clock, Scissors, Droplet,
  Building, ShoppingBag,
} from "lucide-react";

// Neon glow colors per interest — matching the NEX2 design spec
export const INTEREST_COLORS = {
  Technology: "#4AC9FF",
  AI: "#4AC9FF",
  Crypto: "#4AC9FF",
  Startups: "#4AC9FF",
  Business: "#4AC9FF",
  Investing: "#39FF6A",
  "Real Estate": "#4AC9FF",
  Marketing: "#B463FF",
  Freelancing: "#4AC9FF",
  Education: "#4AC9FF",
  Languages: "#4AC9FF",
  Research: "#4AC9FF",
  Science: "#4AC9FF",
  Medicine: "#39FF6A",
  Journalism: "#4AC9FF",
  Photography: "#B463FF",
  Videography: "#B463FF",
  Music: "#B463FF",
  Art: "#B463FF",
  Design: "#B463FF",
  Writing: "#B463FF",
  Movies: "#B463FF",
  Theater: "#B463FF",
  Comedy: "#FFC94A",
  Podcasting: "#B463FF",
  Streaming: "#39FF6A",
  DJing: "#B463FF",
  Creators: "#B463FF",
  Architecture: "#4AC9FF",
  "Interior Design": "#B463FF",
  Fashion: "#FF9A2E",
  Makeup: "#B463FF",
  Skincare: "#B463FF",
  Tattoos: "#FF9A2E",
  Fitness: "#FF9A2E",
  Running: "#FF9A2E",
  Cycling: "#39FF6A",
  Yoga: "#39FF6A",
  Hiking: "#4AC9FF",
  Surfing: "#4AC9FF",
  Fishing: "#4AC9FF",
  Sailing: "#4AC9FF",
  Backpacking: "#4AC9FF",
  Camping: "#39FF6A",
  Skiing: "#4AC9FF",
  Golf: "#39FF6A",
  Sports: "#39FF6A",
  Dance: "#B463FF",
  "Martial Arts": "#FF9A2E",
  Food: "#FFC94A",
  Cooking: "#FFC94A",
  Baking: "#FFC94A",
  Coffee: "#FFC94A",
  Wine: "#B463FF",
  Beer: "#FFC94A",
  Mixology: "#B463FF",
  Nightlife: "#B463FF",
  Travel: "#4AC9FF",
  Cars: "#FF9A2E",
  Motorcycles: "#FF9A2E",
  Sneakers: "#FF9A2E",
  Thrifting: "#FF9A2E",
  Watches: "#4AC9FF",
  Jewelry: "#B463FF",
  Wellness: "#39FF6A",
  Meditation: "#4AC9FF",
  Astrology: "#B463FF",
  Reading: "#39FF6A",
  Philosophy: "#4AC9FF",
  Volunteering: "#39FF6A",
  Pets: "#39FF6A",
  Dogs: "#39FF6A",
  Cats: "#39FF6A",
  Wildlife: "#39FF6A",
  Gardening: "#39FF6A",
  Sustainability: "#39FF6A",
  Climate: "#4AC9FF",
  Gaming: "#39FF6A",
  "Board Games": "#39FF6A",
  Poker: "#39FF6A",
  Chess: "#4AC9FF",
  Anime: "#B463FF",
  Comics: "#B463FF",
  "420": "#39FF6A",
};

export const INTEREST_ICONS = {
  Technology: Cpu,
  AI: Bot,
  Crypto: Bitcoin,
  Startups: Rocket,
  Business: Briefcase,
  Investing: TrendingUp,
  "Real Estate": Building2,
  Marketing: Megaphone,
  Freelancing: Briefcase,
  Education: GraduationCap,
  Languages: Languages,
  Research: Microscope,
  Science: FlaskConical,
  Medicine: Stethoscope,
  Journalism: Newspaper,
  Photography: Camera,
  Videography: Video,
  Music: Music,
  Art: Palette,
  Design: PenTool,
  Writing: PenLine,
  Movies: Film,
  Theater: Drama,
  Comedy: Laugh,
  Podcasting: Podcast,
  Streaming: MonitorPlay,
  DJing: Disc3,
  Creators: Clapperboard,
  Architecture: Building,
  "Interior Design": Armchair,
  Fashion: Shirt,
  Makeup: Brush,
  Skincare: Sparkles,
  Tattoos: Droplet,
  Fitness: Dumbbell,
  Running: Footprints,
  Cycling: Bike,
  Yoga: Flower,
  Hiking: Mountain,
  Surfing: Waves,
  Fishing: Fish,
  Sailing: Ship,
  Backpacking: Backpack,
  Camping: Tent,
  Skiing: Snowflake,
  Golf: Flag,
  Sports: Trophy,
  Dance: PartyPopper,
  "Martial Arts": Hand,
  Food: UtensilsCrossed,
  Cooking: ChefHat,
  Baking: Cake,
  Coffee: Coffee,
  Wine: Wine,
  Beer: Beer,
  Mixology: Martini,
  Nightlife: Moon,
  Travel: Plane,
  Cars: Car,
  Motorcycles: Bike,
  Sneakers: Footprints,
  Thrifting: ShoppingBag,
  Watches: Clock,
  Jewelry: Gem,
  Wellness: HeartPulse,
  Meditation: Brain,
  Astrology: Star,
  Reading: BookOpen,
  Philosophy: Brain,
  Volunteering: HeartHandshake,
  Pets: PawPrint,
  Dogs: Dog,
  Cats: Cat,
  Wildlife: Bird,
  Gardening: Sprout,
  Sustainability: Recycle,
  Climate: CloudSun,
  Gaming: Gamepad2,
  "Board Games": Dices,
  Poker: Spade,
  Chess: Crown,
  Anime: BookMarked,
  Comics: BookMarked,
  "420": Leaf,
};

export function getInterestIcon(interest) {
  return INTEREST_ICONS[interest] || null;
}

export function getInterestColor(interest) {
  return INTEREST_COLORS[interest] || "#4AC9FF";
}