// Demo opportunity data for Opportunity Mode
// Represents realistic business opportunity matches.

export const DEMO_PROVIDERS = [
  {
    id: "demo_provider_1",
    company_name: "Great Investor Loans",
    logo: null,
    industry: "Construction & Real Estate Finance",
    bio: "Private lending firm specializing in ground-up construction, commercial bridge loans, and mixed-use development financing. Nationally licensed with 15+ years of experience funding large-scale projects.",
    provides: ["construction_lending", "commercial_lending", "private_lending", "bridge_financing"],
    looking_for: ["joint_ventures", "property_opportunities"],
    min_deal_size: 25000000,
    max_deal_size: 150000000,
    project_types: ["mixed_use_development", "ground_up_construction", "commercial", "multifamily"],
    markets_served: ["Ohio", "Florida", "Texas", "California", "National"],
    service_area: "national",
    currently_accepting: true,
    is_verified: true,
    response_rate: 94,
    avg_response_time: "2-4 hours",
    website: "https://greatinvestorloans.com",
    visibility: "national",
  },
  {
    id: "demo_provider_2",
    company_name: "Apex Venture Partners",
    logo: null,
    industry: "Venture Capital & Private Equity",
    bio: "Early-to-growth stage venture capital firm backing technology, AI, and real estate technology companies. Seeking high-potential founders building scalable platforms.",
    provides: ["venture_capital_prov", "angel_investment_prov", "private_equity"],
    looking_for: ["business_partners", "software_developers"],
    min_deal_size: 500000,
    max_deal_size: 25000000,
    project_types: ["saas", "ai_automation", "real_estate_tech", "fintech"],
    markets_served: ["Miami", "New York", "San Francisco", "National"],
    service_area: "national",
    currently_accepting: true,
    is_verified: true,
    response_rate: 87,
    avg_response_time: "1-2 days",
    website: "https://apexventure.com",
    visibility: "national",
  },
  {
    id: "demo_provider_3",
    company_name: "BuildRight Construction Group",
    logo: null,
    industry: "Construction & Development",
    bio: "Full-service construction and development company specializing in ground-up commercial and residential projects. Available for joint ventures and project management.",
    provides: ["construction_services", "real_estate_development_prov"],
    looking_for: ["property_opportunities", "business_partners"],
    min_deal_size: 1000000,
    max_deal_size: 50000000,
    project_types: ["mixed_use_development", "ground_up_construction", "commercial", "residential"],
    markets_served: ["Ohio", "Florida", "Texas"],
    service_area: "national",
    currently_accepting: true,
    is_verified: false,
    response_rate: 78,
    avg_response_time: "4-8 hours",
    website: "https://buildright.com",
    visibility: "national",
  },
  {
    id: "demo_provider_4",
    company_name: "LegalShield Partners",
    logo: null,
    industry: "Legal Services",
    bio: "Corporate law firm specializing in business acquisitions, commercial real estate transactions, and construction contract law.",
    provides: ["legal_services_prov"],
    looking_for: ["business_acquisitions"],
    min_deal_size: 0,
    max_deal_size: 0,
    project_types: [],
    markets_served: ["Ohio", "National"],
    service_area: "national",
    currently_accepting: true,
    is_verified: true,
    response_rate: 91,
    avg_response_time: "Same day",
    website: "https://legalshieldpartners.com",
    visibility: "national",
  },
];

export const DEMO_REQUESTS = [
  {
    id: "demo_request_1",
    title: "Looking for Construction Financing",
    industry: "Construction",
    looking_for: ["construction_funding"],
    requested_amount: 100000000,
    project_type: "mixed_use_development",
    location: "Ohio, United States",
    geographic_scope: "national",
    timeline: "Within 90 days",
    additional_details: "Mixed-use development project in Ohio seeking approximately $100M in ground-up construction financing. Project is shovel-ready with permits in place.",
    visibility: "national",
    status: "open",
    created_by_name: "Ohio Construction Co.",
    created_by_verified: false,
  },
  {
    id: "demo_request_2",
    title: "Seeking Software Development Partner",
    industry: "Technology",
    looking_for: ["software_developers", "ai_automation"],
    requested_amount: 500000,
    project_type: "saas",
    location: "Miami, Florida",
    geographic_scope: "national",
    timeline: "Within 60 days",
    additional_details: "Real estate technology startup seeking development partner for AI-powered platform.",
    visibility: "national",
    status: "open",
    created_by_name: "Florida PropTech",
    created_by_verified: true,
  },
];